{{- if include "epoch8-common.serviceAccount.create" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "epoch8-common.serviceAccountName" . }}
  labels:
    {{- include "epoch8-common.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
