{{- if include "simple-app.serviceAccount.create" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simple-app.serviceAccountName" . }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-5"
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
